### ISSUE TITLE
Ganna download url is invalid

### ISSUE THREAD

**Issue by naqushab** [cyberboysumanjay/gaanaapi#3]
Example: https://gaana-song-api.herokuapp.com/result/?url=https://gaana.com/song/meri-aashiqui-5
Returned JSON is :
[{"album":"Meri Aashiqui","artist":"Jubin Nautiyal, Rochak Kohli","bitrate":"96","duration":"4min 40sec","gaana_url":"https://gaana.com/song/meri-aashiqui-5","language":"Hindi","link":"https://vodhlsweb-vh.akamaihd.net/i/songs/76/3215276/30531742/30531742_96.mp4/master.m3u8?set-akamai-hls-revision=5&hdnts=st=1593109861~exp=1593124261~acl=/i/songs/76/3215276/30531742/30531742_96.mp4/*~hmac=4444fbc8f2a4cbbf83032a1ab8bf52d9832432a524844832860536facf5b2e8e","released":"Jun 03, 2020","status":true,"thumb":"https://a10.gaanacdn.com/images/albums/76/3215276/crop_640x640_3215276.jpg","title":"Meri Aashiqui"}]

If you go to the link, the access will be denied.

**Comment by yogirajh007** [comment]
Did the problem resolve??

**Comment by naqushab** [comment]
Not yet. @cyberboysumanjay can you have a look?

**Comment by AnshumanFauzdar** [comment]
Working fine bro @naqushab

**Comment by naqushab** [comment]
Now that I have checked on anything other than macOS, it is playing fine. Still the link works which is all I wanted. Thanks.
Please close the issue.

**Comment by EssentialistStoic** [comment]
When I click on the link, it says access denied. Any solution?
